scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken

    totp:
        enabled: true
        issuer: "MonApp" # Nom affiché dans Google Authenticator
        server_name: "MonApp" # facultatif, pour identification côté serveur
        template: "security/2fa_login.html.twig"
        parameters:
            digits: 6 # nombre de chiffres du code TOTP
            period: 30 # durée de validité d'un code en secondes
            leeway: 1 # autorise +/- 1 période pour compenser un petit décalage
