security:
    password_hashers:
        Symfony\Component\Security\Core\User\UserInterface: "auto"

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        public:
            pattern: ^/vehicles
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\LoginFormAuthenticator

            logout:
                path: app_logout

            remember_me:
                secret: "%kernel.secret%"
                lifetime: 604800
                path: /

    access_control:
        # PUBLIC
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/vehicles, roles: PUBLIC_ACCESS }

        # ADMIN UI (lecture interface uniquement)
        - { path: ^/admin, roles: [ROLE_ADMIN, ROLE_MANAGER] }

        # WORKFLOW ACTIONS (IMPORTANT : séparé de /admin)
        - { path: ^/dossier/.*/transition, roles: IS_AUTHENTICATED_FULLY }

        # fallback sécurité globale admin
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
