framework:
  workflows:
    vehicle_state_machine:
      type: state_machine

      supports:
        - App\Entity\Vehicle

      marking_store:
        type: method
        property: status

      initial_marking: available_sale

      places:
        - available_sale
        - available_rent
        - reserved
        - rented
        - sold
        - ordered
        - maintenance

      transitions:

        reserve:
          from:
            - available_sale
            - available_rent
          to: reserved

        cancel_reservation_to_sale:
          from: reserved
          to: available_sale

        cancel_reservation_to_rent:
          from: reserved
          to: available_rent

        vehicle_rent:
          from:
            - reserved
            - available_rent
          to: rented

        vehicle_return:
          from: rented
          to: available_rent

        vehicle_sell:
          from:
            - available_sale
            - reserved
          to: sold

        vehicle_order:
          from:
            - available_sale
            - available_rent
          to: ordered

        vehicle_send_to_maintenance:
          from:
            - available_sale
            - available_rent
          to: maintenance

        vehicle_back_from_maintenance_to_sale:
          from: maintenance
          to: available_sale

        vehicle_back_from_maintenance_to_rent:
          from: maintenance
          to: available_rent
