framework:
  workflows:
    vehicle_state_machine:
      type: state_machine

      supports:
        - App\Entity\Vehicle

      marking_store:
        type: method
        property: status

      initial_marking: available

      places:
        - available
        - reserved
        - rented
        - sold
        - ordered
        - maintenance

      transitions:
        reserve:
          from: available
          to: reserved

        cancel_reservation:
          from: reserved
          to: available

        vehicle_rent:
          from: reserved
          to: rented

        vehicle_return:
          from: rented
          to: available

        vehicle_sell:
          from: available
          to: sold

        vehicle_order:
          from: available
          to: ordered

        vehicle_send_to_maintenance:
          from: available
          to: maintenance

        vehicle_back_from_maintenance:
          from: maintenance
          to: available
