name: m-motors-prod

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php
    working_dir: /var/www
    volumes:
      - /home/ubuntu/m-motors:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
      - redis
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: ["php-fpm"]
    environment:
      DATABASE_URL: "postgresql://app:app@db:5432/app?serverVersion=16&charset=utf8"

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/prod/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/m-motors:/var/www
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - php
      - certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    entrypoint: >
      sh -c "
        while true; do
          certbot certonly --webroot \
            --webroot-path=/var/www/certbot \
            -d app.m-motors.clickandgo-informatique.com \
            --email mail@clickandgo-informatique.com \
            --agree-tos --non-interactive || true;
          echo 'certbot ok';
          sleep 12h;
        done
      "

  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis

volumes:
  pgdata:

networks:
  default:
    name: m-motors-network
