server {
    listen 80;
    server_name app.m-motors.clickandgo-informatique.com;

    # ACME challenge (Certbot)
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirection vers HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}
