<?php

namespace ContainerNxul548;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NEsmXhsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NEsmXhs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'failed' => ['privates', 'messenger.transport.failed', 'getMessenger_Transport_FailedService', true],
            'messenger.transport.failed' => ['privates', 'messenger.transport.failed', 'getMessenger_Transport_FailedService', true],
        ], [
            'failed' => '?',
            'messenger.transport.failed' => '?',
        ]);

        if (isset($container->privates['.service_locator.NEsmXhs'])) {
            return $container->privates['.service_locator.NEsmXhs'];
        }

        return $container->privates['.service_locator.NEsmXhs'] = $instance;
    }
}
