<?php

namespace ContainerNxul548;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Failure_SendFailedMessageToFailureTransportListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'messenger.failure.send_failed_message_to_failure_transport_listener' shared service.
     *
     * @return \Symfony\Component\Messenger\EventListener\SendFailedMessageToFailureTransportListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/EventListener/SendFailedMessageToFailureTransportListener.php';

        $a = ($container->privates['.service_locator.iU9im4e'] ?? $container->load('get_ServiceLocator_IU9im4eService'));

        if (isset($container->privates['messenger.failure.send_failed_message_to_failure_transport_listener'])) {
            return $container->privates['messenger.failure.send_failed_message_to_failure_transport_listener'];
        }

        $instance = new \Symfony\Component\Messenger\EventListener\SendFailedMessageToFailureTransportListener($a, ($container->privates['monolog.logger.messenger'] ?? $container->load('getMonolog_Logger_MessengerService')));

        if (isset($container->privates['messenger.failure.send_failed_message_to_failure_transport_listener'])) {
            return $container->privates['messenger.failure.send_failed_message_to_failure_transport_listener'];
        }

        return $container->privates['messenger.failure.send_failed_message_to_failure_transport_listener'] = $instance;
    }
}
