<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260623163545 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE body_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, slug VARCHAR(120) NOT NULL, position INT NOT NULL, icon VARCHAR(50) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D95AEB4B5E237E06 ON body_type (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D95AEB4B989D9B62 ON body_type (slug)');
        $this->addSql('CREATE TABLE brand (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1C52F9585E237E06 ON brand (name)');
        $this->addSql('CREATE TABLE color (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_665648E95E237E06 ON color (name)');
        $this->addSql('CREATE TABLE customer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, customer_code VARCHAR(10) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, email VARCHAR(180) NOT NULL, phone_number1 VARCHAR(20) DEFAULT NULL, phone_number2 VARCHAR(20) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, zip_code VARCHAR(7) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, address_details VARCHAR(255) DEFAULT NULL, country VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_81398E09238494EF ON customer (customer_code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_81398E09E7927C74 ON customer (email)');
        $this->addSql('CREATE TABLE dossier (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, dossier_code VARCHAR(50) NOT NULL, status VARCHAR(50) NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cancelled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, customer_id INT NOT NULL, vehicle_id INT DEFAULT NULL, assigned_to_id INT DEFAULT NULL, validated_by_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3D48E037FB2FF1EB ON dossier (dossier_code)');
        $this->addSql('CREATE INDEX IDX_3D48E0379395C3F3 ON dossier (customer_id)');
        $this->addSql('CREATE INDEX IDX_3D48E037545317D1 ON dossier (vehicle_id)');
        $this->addSql('CREATE INDEX IDX_3D48E037F4BD7827 ON dossier (assigned_to_id)');
        $this->addSql('CREATE INDEX IDX_3D48E037C69DE5E5 ON dossier (validated_by_id)');
        $this->addSql('CREATE INDEX IDX_3D48E037B03A8386 ON dossier (created_by_id)');
        $this->addSql('CREATE TABLE dossier_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(50) NOT NULL, message TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, dossier_id INT NOT NULL, user_id INT DEFAULT NULL, document_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5B98E53E611C0C56 ON dossier_audit (dossier_id)');
        $this->addSql('CREATE INDEX IDX_5B98E53EA76ED395 ON dossier_audit (user_id)');
        $this->addSql('CREATE INDEX IDX_5B98E53EC33F7837 ON dossier_audit (document_id)');
        $this->addSql('CREATE TABLE dossier_document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, document_type VARCHAR(255) NOT NULL, original_name VARCHAR(255) NOT NULL, file_name VARCHAR(255) NOT NULL, path VARCHAR(500) NOT NULL, status VARCHAR(255) NOT NULL, validated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, dossier_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F0296801611C0C56 ON dossier_document (dossier_id)');
        $this->addSql('CREATE TABLE dossier_workflow_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, transition VARCHAR(100) NOT NULL, from_status VARCHAR(100) NOT NULL, to_status VARCHAR(100) NOT NULL, user_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, dossier_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_56315DFC611C0C56 ON dossier_workflow_log (dossier_id)');
        $this->addSql('CREATE TABLE favorite (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, vehicle_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_68C58ED9A76ED395 ON favorite (user_id)');
        $this->addSql('CREATE INDEX IDX_68C58ED9545317D1 ON favorite (vehicle_id)');
        $this->addSql('CREATE TABLE feature (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(100) NOT NULL, label VARCHAR(100) NOT NULL, category_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1FD7756677153098 ON feature (code)');
        $this->addSql('CREATE INDEX IDX_1FD7756612469DE2 ON feature (category_id)');
        $this->addSql('CREATE TABLE feature_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(100) NOT NULL, label VARCHAR(100) NOT NULL, position INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7FA1B6FE77153098 ON feature_category (code)');
        $this->addSql('CREATE TABLE financing (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, type VARCHAR(20) NOT NULL, leasing_type VARCHAR(10) DEFAULT NULL, amount INT DEFAULT NULL, duration_months INT DEFAULT NULL, monthly_payment DOUBLE PRECISION DEFAULT NULL, decided_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, dossier_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7ECA6FEB611C0C56 ON financing (dossier_id)');
        $this->addSql('CREATE TABLE fuel_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9CA10F385E237E06 ON fuel_type (name)');
        $this->addSql('CREATE TABLE gear_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3AF26DA85E237E06 ON gear_type (name)');
        $this->addSql('CREATE TABLE image (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, filename VARCHAR(255) NOT NULL, thumbnail VARCHAR(255) NOT NULL, original_name VARCHAR(255) NOT NULL, mime_type VARCHAR(100) NOT NULL, size INT NOT NULL, position INT NOT NULL, is_featured BOOLEAN NOT NULL, image_path VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, vehicle_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C53D045F545317D1 ON image (vehicle_id)');
        $this->addSql('CREATE TABLE maintenance (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, description VARCHAR(255) NOT NULL, mileage INT DEFAULT NULL, vehicle_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2F84F8E9545317D1 ON maintenance (vehicle_id)');
        $this->addSql('CREATE TABLE model (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, brand_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D79572D944F5D008 ON model (brand_id)');
        $this->addSql('CREATE TABLE rental (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, vehicle_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1619C27D545317D1 ON rental (vehicle_id)');
        $this->addSql('CREATE TABLE sale (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, price DOUBLE PRECISION NOT NULL, sold_at DATE NOT NULL, vehicle_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E54BC005545317D1 ON sale (vehicle_id)');
        $this->addSql('CREATE TABLE supplier (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, address VARCHAR(255) DEFAULT NULL, city VARCHAR(100) DEFAULT NULL, postal_code VARCHAR(10) DEFAULT NULL, country VARCHAR(100) DEFAULT NULL, siret VARCHAR(14) DEFAULT NULL, email VARCHAR(180) DEFAULT NULL, phone VARCHAR(30) DEFAULT NULL, type VARCHAR(255) NOT NULL, average_delivery_delay INT DEFAULT NULL, rating NUMERIC(2, 1) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9B2A6C7E5E237E06 ON supplier (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9B2A6C7E26E94372 ON supplier (siret)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_verified BOOLEAN NOT NULL, nickname VARCHAR(50) DEFAULT NULL, totp_secret VARCHAR(255) DEFAULT NULL, google2_fasecret VARCHAR(255) DEFAULT NULL, is2_faenabled BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, customer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D6499395C3F3 ON "user" (customer_id)');
        $this->addSql('CREATE TABLE variant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, model_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F143BFAD7975B7E7 ON variant (model_id)');
        $this->addSql('CREATE TABLE vehicle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, usage_type VARCHAR(255) NOT NULL, first_registration_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, mileage INT DEFAULT NULL, price INT NOT NULL, vin VARCHAR(17) NOT NULL, registration_number VARCHAR(15) DEFAULT NULL, is_featured BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, vehicle_model_id INT DEFAULT NULL, fuel_type_id INT DEFAULT NULL, gear_type_id INT DEFAULT NULL, color_id INT DEFAULT NULL, supplier_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1B80E486B1085141 ON vehicle (vin)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1B80E48638CEDFBE ON vehicle (registration_number)');
        $this->addSql('CREATE INDEX IDX_1B80E486A467B873 ON vehicle (vehicle_model_id)');
        $this->addSql('CREATE INDEX IDX_1B80E4866A70FE35 ON vehicle (fuel_type_id)');
        $this->addSql('CREATE INDEX IDX_1B80E48632CA4F08 ON vehicle (gear_type_id)');
        $this->addSql('CREATE INDEX IDX_1B80E4867ADA1FB5 ON vehicle (color_id)');
        $this->addSql('CREATE INDEX IDX_1B80E4862ADD6D8C ON vehicle (supplier_id)');
        $this->addSql('CREATE TABLE vehicle_vehicle_badge (vehicle_id INT NOT NULL, vehicle_badge_id INT NOT NULL, PRIMARY KEY (vehicle_id, vehicle_badge_id))');
        $this->addSql('CREATE INDEX IDX_CB8E953B545317D1 ON vehicle_vehicle_badge (vehicle_id)');
        $this->addSql('CREATE INDEX IDX_CB8E953B2AB0CD68 ON vehicle_vehicle_badge (vehicle_badge_id)');
        $this->addSql('CREATE TABLE vehicle_badge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(100) NOT NULL, label VARCHAR(255) NOT NULL, category VARCHAR(255) NOT NULL, priority INT NOT NULL, color VARCHAR(7) DEFAULT NULL, icon VARCHAR(255) DEFAULT NULL, is_active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_vehicle_badge_code ON vehicle_badge (code)');
        $this->addSql('CREATE TABLE vehicle_model (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, euro_norm VARCHAR(20) DEFAULT NULL, power_hp INT DEFAULT NULL, power_fiscal DOUBLE PRECISION DEFAULT NULL, consumption DOUBLE PRECISION DEFAULT NULL, co2 INT DEFAULT NULL, cnit VARCHAR(50) DEFAULT NULL, utac_code VARCHAR(50) DEFAULT NULL, homologation_date DATE DEFAULT NULL, mass_min INT DEFAULT NULL, mass_max INT DEFAULT NULL, brand_id INT NOT NULL, model_id INT NOT NULL, variant_id INT DEFAULT NULL, fuel_type_id INT DEFAULT NULL, gear_type_id INT DEFAULT NULL, body_type_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B53AF23544F5D008 ON vehicle_model (brand_id)');
        $this->addSql('CREATE INDEX IDX_B53AF2357975B7E7 ON vehicle_model (model_id)');
        $this->addSql('CREATE INDEX IDX_B53AF2353B69A9AF ON vehicle_model (variant_id)');
        $this->addSql('CREATE INDEX IDX_B53AF2356A70FE35 ON vehicle_model (fuel_type_id)');
        $this->addSql('CREATE INDEX IDX_B53AF23532CA4F08 ON vehicle_model (gear_type_id)');
        $this->addSql('CREATE INDEX IDX_B53AF2352CBA3505 ON vehicle_model (body_type_id)');
        $this->addSql('CREATE TABLE vehicle_model_feature (vehicle_model_id INT NOT NULL, feature_id INT NOT NULL, PRIMARY KEY (vehicle_model_id, feature_id))');
        $this->addSql('CREATE INDEX IDX_2895415DA467B873 ON vehicle_model_feature (vehicle_model_id)');
        $this->addSql('CREATE INDEX IDX_2895415D60E4B879 ON vehicle_model_feature (feature_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE dossier ADD CONSTRAINT FK_3D48E0379395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dossier ADD CONSTRAINT FK_3D48E037545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id)');
        $this->addSql('ALTER TABLE dossier ADD CONSTRAINT FK_3D48E037F4BD7827 FOREIGN KEY (assigned_to_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE dossier ADD CONSTRAINT FK_3D48E037C69DE5E5 FOREIGN KEY (validated_by_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE dossier ADD CONSTRAINT FK_3D48E037B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE dossier_audit ADD CONSTRAINT FK_5B98E53E611C0C56 FOREIGN KEY (dossier_id) REFERENCES dossier (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dossier_audit ADD CONSTRAINT FK_5B98E53EA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE dossier_audit ADD CONSTRAINT FK_5B98E53EC33F7837 FOREIGN KEY (document_id) REFERENCES dossier_document (id)');
        $this->addSql('ALTER TABLE dossier_document ADD CONSTRAINT FK_F0296801611C0C56 FOREIGN KEY (dossier_id) REFERENCES dossier (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dossier_workflow_log ADD CONSTRAINT FK_56315DFC611C0C56 FOREIGN KEY (dossier_id) REFERENCES dossier (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE favorite ADD CONSTRAINT FK_68C58ED9A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE favorite ADD CONSTRAINT FK_68C58ED9545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE feature ADD CONSTRAINT FK_1FD7756612469DE2 FOREIGN KEY (category_id) REFERENCES feature_category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE financing ADD CONSTRAINT FK_7ECA6FEB611C0C56 FOREIGN KEY (dossier_id) REFERENCES dossier (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE image ADD CONSTRAINT FK_C53D045F545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE maintenance ADD CONSTRAINT FK_2F84F8E9545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE model ADD CONSTRAINT FK_D79572D944F5D008 FOREIGN KEY (brand_id) REFERENCES brand (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rental ADD CONSTRAINT FK_1619C27D545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sale ADD CONSTRAINT FK_E54BC005545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D6499395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE variant ADD CONSTRAINT FK_F143BFAD7975B7E7 FOREIGN KEY (model_id) REFERENCES model (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vehicle ADD CONSTRAINT FK_1B80E486A467B873 FOREIGN KEY (vehicle_model_id) REFERENCES vehicle_model (id)');
        $this->addSql('ALTER TABLE vehicle ADD CONSTRAINT FK_1B80E4866A70FE35 FOREIGN KEY (fuel_type_id) REFERENCES fuel_type (id)');
        $this->addSql('ALTER TABLE vehicle ADD CONSTRAINT FK_1B80E48632CA4F08 FOREIGN KEY (gear_type_id) REFERENCES gear_type (id)');
        $this->addSql('ALTER TABLE vehicle ADD CONSTRAINT FK_1B80E4867ADA1FB5 FOREIGN KEY (color_id) REFERENCES color (id)');
        $this->addSql('ALTER TABLE vehicle ADD CONSTRAINT FK_1B80E4862ADD6D8C FOREIGN KEY (supplier_id) REFERENCES supplier (id)');
        $this->addSql('ALTER TABLE vehicle_vehicle_badge ADD CONSTRAINT FK_CB8E953B545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE vehicle_vehicle_badge ADD CONSTRAINT FK_CB8E953B2AB0CD68 FOREIGN KEY (vehicle_badge_id) REFERENCES vehicle_badge (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE vehicle_model ADD CONSTRAINT FK_B53AF23544F5D008 FOREIGN KEY (brand_id) REFERENCES brand (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vehicle_model ADD CONSTRAINT FK_B53AF2357975B7E7 FOREIGN KEY (model_id) REFERENCES model (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vehicle_model ADD CONSTRAINT FK_B53AF2353B69A9AF FOREIGN KEY (variant_id) REFERENCES variant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vehicle_model ADD CONSTRAINT FK_B53AF2356A70FE35 FOREIGN KEY (fuel_type_id) REFERENCES fuel_type (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vehicle_model ADD CONSTRAINT FK_B53AF23532CA4F08 FOREIGN KEY (gear_type_id) REFERENCES gear_type (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vehicle_model ADD CONSTRAINT FK_B53AF2352CBA3505 FOREIGN KEY (body_type_id) REFERENCES body_type (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vehicle_model_feature ADD CONSTRAINT FK_2895415DA467B873 FOREIGN KEY (vehicle_model_id) REFERENCES vehicle_model (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE vehicle_model_feature ADD CONSTRAINT FK_2895415D60E4B879 FOREIGN KEY (feature_id) REFERENCES feature (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE dossier DROP CONSTRAINT FK_3D48E0379395C3F3');
        $this->addSql('ALTER TABLE dossier DROP CONSTRAINT FK_3D48E037545317D1');
        $this->addSql('ALTER TABLE dossier DROP CONSTRAINT FK_3D48E037F4BD7827');
        $this->addSql('ALTER TABLE dossier DROP CONSTRAINT FK_3D48E037C69DE5E5');
        $this->addSql('ALTER TABLE dossier DROP CONSTRAINT FK_3D48E037B03A8386');
        $this->addSql('ALTER TABLE dossier_audit DROP CONSTRAINT FK_5B98E53E611C0C56');
        $this->addSql('ALTER TABLE dossier_audit DROP CONSTRAINT FK_5B98E53EA76ED395');
        $this->addSql('ALTER TABLE dossier_audit DROP CONSTRAINT FK_5B98E53EC33F7837');
        $this->addSql('ALTER TABLE dossier_document DROP CONSTRAINT FK_F0296801611C0C56');
        $this->addSql('ALTER TABLE dossier_workflow_log DROP CONSTRAINT FK_56315DFC611C0C56');
        $this->addSql('ALTER TABLE favorite DROP CONSTRAINT FK_68C58ED9A76ED395');
        $this->addSql('ALTER TABLE favorite DROP CONSTRAINT FK_68C58ED9545317D1');
        $this->addSql('ALTER TABLE feature DROP CONSTRAINT FK_1FD7756612469DE2');
        $this->addSql('ALTER TABLE financing DROP CONSTRAINT FK_7ECA6FEB611C0C56');
        $this->addSql('ALTER TABLE image DROP CONSTRAINT FK_C53D045F545317D1');
        $this->addSql('ALTER TABLE maintenance DROP CONSTRAINT FK_2F84F8E9545317D1');
        $this->addSql('ALTER TABLE model DROP CONSTRAINT FK_D79572D944F5D008');
        $this->addSql('ALTER TABLE rental DROP CONSTRAINT FK_1619C27D545317D1');
        $this->addSql('ALTER TABLE sale DROP CONSTRAINT FK_E54BC005545317D1');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D6499395C3F3');
        $this->addSql('ALTER TABLE variant DROP CONSTRAINT FK_F143BFAD7975B7E7');
        $this->addSql('ALTER TABLE vehicle DROP CONSTRAINT FK_1B80E486A467B873');
        $this->addSql('ALTER TABLE vehicle DROP CONSTRAINT FK_1B80E4866A70FE35');
        $this->addSql('ALTER TABLE vehicle DROP CONSTRAINT FK_1B80E48632CA4F08');
        $this->addSql('ALTER TABLE vehicle DROP CONSTRAINT FK_1B80E4867ADA1FB5');
        $this->addSql('ALTER TABLE vehicle DROP CONSTRAINT FK_1B80E4862ADD6D8C');
        $this->addSql('ALTER TABLE vehicle_vehicle_badge DROP CONSTRAINT FK_CB8E953B545317D1');
        $this->addSql('ALTER TABLE vehicle_vehicle_badge DROP CONSTRAINT FK_CB8E953B2AB0CD68');
        $this->addSql('ALTER TABLE vehicle_model DROP CONSTRAINT FK_B53AF23544F5D008');
        $this->addSql('ALTER TABLE vehicle_model DROP CONSTRAINT FK_B53AF2357975B7E7');
        $this->addSql('ALTER TABLE vehicle_model DROP CONSTRAINT FK_B53AF2353B69A9AF');
        $this->addSql('ALTER TABLE vehicle_model DROP CONSTRAINT FK_B53AF2356A70FE35');
        $this->addSql('ALTER TABLE vehicle_model DROP CONSTRAINT FK_B53AF23532CA4F08');
        $this->addSql('ALTER TABLE vehicle_model DROP CONSTRAINT FK_B53AF2352CBA3505');
        $this->addSql('ALTER TABLE vehicle_model_feature DROP CONSTRAINT FK_2895415DA467B873');
        $this->addSql('ALTER TABLE vehicle_model_feature DROP CONSTRAINT FK_2895415D60E4B879');
        $this->addSql('DROP TABLE body_type');
        $this->addSql('DROP TABLE brand');
        $this->addSql('DROP TABLE color');
        $this->addSql('DROP TABLE customer');
        $this->addSql('DROP TABLE dossier');
        $this->addSql('DROP TABLE dossier_audit');
        $this->addSql('DROP TABLE dossier_document');
        $this->addSql('DROP TABLE dossier_workflow_log');
        $this->addSql('DROP TABLE favorite');
        $this->addSql('DROP TABLE feature');
        $this->addSql('DROP TABLE feature_category');
        $this->addSql('DROP TABLE financing');
        $this->addSql('DROP TABLE fuel_type');
        $this->addSql('DROP TABLE gear_type');
        $this->addSql('DROP TABLE image');
        $this->addSql('DROP TABLE maintenance');
        $this->addSql('DROP TABLE model');
        $this->addSql('DROP TABLE rental');
        $this->addSql('DROP TABLE sale');
        $this->addSql('DROP TABLE supplier');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE variant');
        $this->addSql('DROP TABLE vehicle');
        $this->addSql('DROP TABLE vehicle_vehicle_badge');
        $this->addSql('DROP TABLE vehicle_badge');
        $this->addSql('DROP TABLE vehicle_model');
        $this->addSql('DROP TABLE vehicle_model_feature');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
