<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260429102301 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE vehicle_model_stock (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, vehicle_model_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FB4E0BE1A467B873 ON vehicle_model_stock (vehicle_model_id)');
        $this->addSql('ALTER TABLE vehicle_model_stock ADD CONSTRAINT FK_FB4E0BE1A467B873 FOREIGN KEY (vehicle_model_id) REFERENCES vehicle_model (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE vehicle_model_stock DROP CONSTRAINT FK_FB4E0BE1A467B873');
        $this->addSql('DROP TABLE vehicle_model_stock');
    }
}
