<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260429105903 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE vehicle_model_stock DROP CONSTRAINT fk_fb4e0be1a467b873');
        $this->addSql('DROP TABLE vehicle_model_stock');
        $this->addSql('DROP INDEX idx_b53af235a9c90410');
        $this->addSql('DROP INDEX idx_b53af2353b948065');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE vehicle_model_stock (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, vehicle_model_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_fb4e0be1a467b873 ON vehicle_model_stock (vehicle_model_id)');
        $this->addSql('ALTER TABLE vehicle_model_stock ADD CONSTRAINT fk_fb4e0be1a467b873 FOREIGN KEY (vehicle_model_id) REFERENCES vehicle_model (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_b53af235a9c90410 ON vehicle_model (cnit)');
        $this->addSql('CREATE INDEX idx_b53af2353b948065 ON vehicle_model (utac_code)');
    }
}
