parameters:
    dossier_upload_dir: "%kernel.project_dir%/public/uploads"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $uploadDir: "%dossier_upload_dir%"

    # =========================================================
    # AUTOWIRE GLOBAL APP
    # =========================================================

    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Migrations/"
            - "../src/Tests/"
            - "../src/Kernel.php"

    # =========================================================
    # UPLOAD SERVICE
    # =========================================================

    App\Service\DossierDocumentUploadService: ~

    # =========================================================
    # TYPE RESOLVER (METIER)
    # =========================================================

    App\Service\DossierDocumentTypeResolver: ~

    # =========================================================
    # WORKFLOW GUARD
    # =========================================================

    App\Workflow\Guard\DossierWorkflowGuard:
        tags:
            - {
                  name: kernel.event_listener,
                  event: workflow.dossier.guard.submit_documents,
                  method: guardSubmitDocuments,
              }

    App\Listener\DocumentUploadedListener:
    tags:
        - {
              name: kernel.event_listener,
              event: App\Event\DocumentUploadedEvent,
              method: __invoke,
          }
