<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLkYZ7w7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLkYZ7w7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLkYZ7w7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLkYZ7w7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLkYZ7w7\App_KernelDevDebugContainer([
    'container.build_hash' => 'LkYZ7w7',
    'container.build_id' => '3eb87122',
    'container.build_time' => 1769431136,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLkYZ7w7');
